services:
  db:
    image: postgres:16-alpine
    container_name: maybe-db
    environment:
      POSTGRES_USER: ${PG_USER:-user}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-password}
      POSTGRES_DB: ${PG_DATABASE:-finance}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: maybe-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
